### ISSUE TITLE
WebRequest no longer working (Clickatell API)

### ISSUE THREAD

**Issue by Matthiee** [MatthiWare/SmsAndCall#1]
When using the Clickatell API the WebRequest is no longer working.
Sending the request manually using Postman still works. There must be some setting causing this problem.

Feel free to open a PR with a fix!

**Comment by AlexisFonnegra** [comment]
Buenos Dias. Amigo tengo un problema al enviar SMS con clickatell.
m_lastResponse = await m_currentApi.SendSmsAsync(from, to, body);

Se produjo una excepción de tipo 'System.Net.WebException' en mscorlib.dll pero no se controló en el código del usuario

![error](https://user-images.githubusercontent.com/26337058/32951084-a78cad16-cb76-11e7-8843-5a591af149a5.jpg)

**Comment by Matthiee** [comment]
@AlexisFonnegra I merged a fix for your problem (see #3 ).

**Comment by AlexisFonnegra** [comment]
Amigo ya hace el intento de enviar, aparece es el problemas de 
not Enough money-you dont have enoug money to complete this operation

**Comment by Matthiee** [comment]
@AlexisFonnegra You can only send free text messages to test phone numbers. 
Check you test phone settings of the SMS Integration you are using. 

If you want to send text messages to non test phone numbers you need to have credit on Clickatell.

**Comment by AlexisFonnegra** [comment]
Ah bueno amigo, usted es excelente mil gracias
